# Generated by Django 4.1.3 on 2022-11-30 14:19

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import mypost.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('avatar', models.FileField(upload_to='', validators=[mypost.models.custom_validator], verbose_name='Profil rasmi')),
                ('login', models.CharField(max_length=50, unique=True, verbose_name='Foydalanuvchi taxallusi')),
                ('about', models.TextField(max_length=1000, verbose_name='Foydalanuvchi haqida ma`lumot')),
                ('role', models.CharField(choices=[('arxitektor', 'arxitektor'), ('3d dizayner', '3d dizayner'), ('arxitektor va dizayner', 'arxitektor va dizayner'), ('Buyurtmachi', 'Buyurtmachi')], max_length=30, verbose_name='Foydalanuvchi sohasi')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'Foydalanuvchi',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Yo`nalish',
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_of_job', models.CharField(choices=[('arxitektor', 'arxitektor'), ('3d dizayner', '3d dizayner'), ('arxitektor va dizayner', 'arxitektor va dizayner')], max_length=30, verbose_name='Ish o`rinlari')),
                ('address', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=13)),
                ('name_of_company', models.CharField(max_length=50, null=True)),
            ],
            options={
                'db_table': 'Bo`sh ish o`rinlari',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files', validators=[mypost.models.custom_validator_file], verbose_name='Fayl yuklash')),
                ('image', models.ImageField(upload_to='media', verbose_name='Rasm yuklash')),
                ('created_date', models.TimeField(auto_now=True, verbose_name='Yuklangan vaqti')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mypost.category', verbose_name='Yo`nalish')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'db_table': 'Postlar',
            },
        ),
        migrations.CreateModel(
            name='CommentsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)], verbose_name='Baholash')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('text', models.TextField(max_length=200, verbose_name='Izoh matni')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mypost.post', verbose_name='Post id raqami')),
                ('rating_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Izoh muallifi')),
            ],
            options={
                'db_table': 'Izohlar',
            },
        ),
        migrations.CreateModel(
            name='Chatting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=1000)),
                ('time', models.TimeField(auto_now=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yuboruvchi', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qabulqiluvchi', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Yozishmalar',
            },
        ),
    ]
